# Customer Churn Prediction

## 2. Data Cleaning

### Business Objective

The objective of this phase is to identify and resolve data quality issues before analysis and machine learning. Clean and reliable data improves the accuracy of insights and predictive models.

The following tasks will be performed:

- Check duplicate records
- Identify missing values
- Detect hidden missing values
- Correct incorrect data types
- Prepare the dataset for exploratory data analysis (EDA)

In [1]:
import pandas as pd
import numpy as np

In [3]:
df = pd.read_csv("E:/data_science/projects/customer_churn_prediction/data/raw/telco_customer_churn.csv")

## 2.1 Check for Duplicate Records

Duplicate records can lead to incorrect analysis and biased machine learning models. Before cleaning the dataset, we verify whether duplicate customer records exist.

In [4]:
# Check duplicate records
duplicate_count = df.duplicated().sum()

print(f"Number of duplicate records: {duplicate_count}")

Number of duplicate records: 0

## 2.2 Check Missing Values

In [5]:
# Check missing values
df.isnull().sum()

customerID          0
gender              0
SeniorCitizen       0
Partner             0
Dependents          0
tenure              0
PhoneService        0
MultipleLines       0
InternetService     0
OnlineSecurity      0
OnlineBackup        0
DeviceProtection    0
TechSupport         0
StreamingTV         0
StreamingMovies     0
Contract            0
PaperlessBilling    0
PaymentMethod       0
MonthlyCharges      0
TotalCharges        0
Churn               0
dtype: int64

## 2.3 Investigate Hidden Missing Values

In [6]:
# Check for blank values in TotalCharges
(df["TotalCharges"] == " ").sum()

np.int64(11)

In [7]:
# Display rows where TotalCharges is blank
df[df["TotalCharges"] == " "]

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
488,4472-LVYGI,Female,0,Yes,Yes,0,No,No phone service,DSL,Yes,...,Yes,Yes,Yes,No,Two year,Yes,Bank transfer (automatic),52.55,,No
753,3115-CZMZD,Male,0,No,Yes,0,Yes,No,No,No internet service,...,No internet service,No internet service,No internet service,No internet service,Two year,No,Mailed check,20.25,,No
936,5709-LVOEQ,Female,0,Yes,Yes,0,Yes,No,DSL,Yes,...,Yes,No,Yes,Yes,Two year,No,Mailed check,80.85,,No
1082,4367-NUYAO,Male,0,Yes,Yes,0,Yes,Yes,No,No internet service,...,No internet service,No internet service,No internet service,No internet service,Two year,No,Mailed check,25.75,,No
1340,1371-DWPAZ,Female,0,Yes,Yes,0,No,No phone service,DSL,Yes,...,Yes,Yes,Yes,No,Two year,No,Credit card (automatic),56.05,,No
3331,7644-OMVMY,Male,0,Yes,Yes,0,Yes,No,No,No internet service,...,No internet service,No internet service,No internet service,No internet service,Two year,No,Mailed check,19.85,,No
3826,3213-VVOLG,Male,0,Yes,Yes,0,Yes,Yes,No,No internet service,...,No internet service,No internet service,No internet service,No internet service,Two year,No,Mailed check,25.35,,No
4380,2520-SGTTA,Female,0,Yes,Yes,0,Yes,No,No,No internet service,...,No internet service,No internet service,No internet service,No internet service,Two year,No,Mailed check,20.00,,No
5218,2923-ARZLG,Male,0,Yes,Yes,0,Yes,No,No,No internet service,...,No internet service,No internet service,No internet service,No internet service,One year,Yes,Mailed check,19.70,,No
6670,4075-WKNIU,Female,0,Yes,Yes,0,Yes,Yes,DSL,No,...,Yes,Yes,Yes,No,Two year,No,Mailed check,73.35,,No
6754,2775-SEFEE,Male,0,No,Yes,0,Yes,Yes,DSL,Yes,...,No,Yes,No,No,Two year,Yes,Bank transfer (automatic),61.90,,No

In [8]:
df[df["TotalCharges"] == " "][["customerID", "tenure", "MonthlyCharges", "TotalCharges", "Churn"]]

      customerID  tenure  MonthlyCharges TotalCharges Churn
488   4472-LVYGI       0           52.55                 No
753   3115-CZMZD       0           20.25                 No
936   5709-LVOEQ       0           80.85                 No
1082  4367-NUYAO       0           25.75                 No
1340  1371-DWPAZ       0           56.05                 No
3331  7644-OMVMY       0           19.85                 No
3826  3213-VVOLG       0           25.35                 No
4380  2520-SGTTA       0           20.00                 No
5218  2923-ARZLG       0           19.70                 No
6670  4075-WKNIU       0           73.35                 No
6754  2775-SEFEE       0           61.90                 No

In [9]:
import numpy as np

df["TotalCharges"] = df["TotalCharges"].replace(" ", np.nan)

In [10]:
df.isnull().sum()

customerID           0
gender               0
SeniorCitizen        0
Partner              0
Dependents           0
tenure               0
PhoneService         0
MultipleLines        0
InternetService      0
OnlineSecurity       0
OnlineBackup         0
DeviceProtection     0
TechSupport          0
StreamingTV          0
StreamingMovies      0
Contract             0
PaperlessBilling     0
PaymentMethod        0
MonthlyCharges       0
TotalCharges        11
Churn                0
dtype: int64

### Observation

Although `df.info()` and `df.isnull().sum()` initially indicated no missing values, further investigation revealed that the `TotalCharges` column contained 11 blank string values (`" "`).

These blank strings were converted to `NaN` so they could be properly identified and handled during the data cleaning process.

In [11]:
df[df["TotalCharges"].isnull()]

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
488,4472-LVYGI,Female,0,Yes,Yes,0,No,No phone service,DSL,Yes,...,Yes,Yes,Yes,No,Two year,Yes,Bank transfer (automatic),52.55,NaN,No
753,3115-CZMZD,Male,0,No,Yes,0,Yes,No,No,No internet service,...,No internet service,No internet service,No internet service,No internet service,Two year,No,Mailed check,20.25,NaN,No
936,5709-LVOEQ,Female,0,Yes,Yes,0,Yes,No,DSL,Yes,...,Yes,No,Yes,Yes,Two year,No,Mailed check,80.85,NaN,No
1082,4367-NUYAO,Male,0,Yes,Yes,0,Yes,Yes,No,No internet service,...,No internet service,No internet service,No internet service,No internet service,Two year,No,Mailed check,25.75,NaN,No
1340,1371-DWPAZ,Female,0,Yes,Yes,0,No,No phone service,DSL,Yes,...,Yes,Yes,Yes,No,Two year,No,Credit card (automatic),56.05,NaN,No
3331,7644-OMVMY,Male,0,Yes,Yes,0,Yes,No,No,No internet service,...,No internet service,No internet service,No internet service,No internet service,Two year,No,Mailed check,19.85,NaN,No
3826,3213-VVOLG,Male,0,Yes,Yes,0,Yes,Yes,No,No internet service,...,No internet service,No internet service,No internet service,No internet service,Two year,No,Mailed check,25.35,NaN,No
4380,2520-SGTTA,Female,0,Yes,Yes,0,Yes,No,No,No internet service,...,No internet service,No internet service,No internet service,No internet service,Two year,No,Mailed check,20.00,NaN,No
5218,2923-ARZLG,Male,0,Yes,Yes,0,Yes,No,No,No internet service,...,No internet service,No internet service,No internet service,No internet service,One year,Yes,Mailed check,19.70,NaN,No
6670,4075-WKNIU,Female,0,Yes,Yes,0,Yes,Yes,DSL,No,...,Yes,Yes,Yes,No,Two year,No,Mailed check,73.35,NaN,No
6754,2775-SEFEE,Male,0,No,Yes,0,Yes,Yes,DSL,Yes,...,No,Yes,No,No,Two year,Yes,Bank transfer (automatic),61.90,NaN,No

In [12]:
df[df["TotalCharges"].isnull()][[
    "customerID",
    "tenure",
    "MonthlyCharges",
    "Contract",
    "Churn"
]]

      customerID  tenure  MonthlyCharges  Contract Churn
488   4472-LVYGI       0           52.55  Two year    No
753   3115-CZMZD       0           20.25  Two year    No
936   5709-LVOEQ       0           80.85  Two year    No
1082  4367-NUYAO       0           25.75  Two year    No
1340  1371-DWPAZ       0           56.05  Two year    No
3331  7644-OMVMY       0           19.85  Two year    No
3826  3213-VVOLG       0           25.35  Two year    No
4380  2520-SGTTA       0           20.00  Two year    No
5218  2923-ARZLG       0           19.70  One year    No
6670  4075-WKNIU       0           73.35  Two year    No
6754  2775-SEFEE       0           61.90  Two year    No

### 2.4 Handling Missing Values

The `TotalCharges` column contained 11 hidden missing values represented as blank strings. These were converted to `NaN`.

Since these records account for only 11 out of 7,043 customers (approximately 0.16% of the dataset), removing them has a negligible impact on the analysis while preserving data quality.

In [13]:
# Remove rows with missing TotalCharges
df = df.dropna(subset=["TotalCharges"])

# Check dataset shape
df.shape

(7032, 21)

### 2.5 Convert Data Types

The `TotalCharges` column was originally stored as a string because of hidden blank values. After removing those records, the column is converted to a numeric data type for further analysis.

In [14]:
# Convert TotalCharges to numeric
df["TotalCharges"] = pd.to_numeric(df["TotalCharges"])

In [15]:
df.info()

<class 'pandas.DataFrame'>
Index: 7032 entries, 0 to 7042
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customerID        7032 non-null   str
 1   gender            7032 non-null   str
 2   SeniorCitizen     7032 non-null   int64
 3   Partner           7032 non-null   str
 4   Dependents        7032 non-null   str
 5   tenure            7032 non-null   int64
 6   PhoneService      7032 non-null   str
 7   MultipleLines     7032 non-null   str
 8   InternetService   7032 non-null   str
 9   OnlineSecurity    7032 non-null   str
 10  OnlineBackup      7032 non-null   str
 11  DeviceProtection  7032 non-null   str
 12  TechSupport       7032 non-null   str
 13  StreamingTV       7032 non-null   str
 14  StreamingMovies   7032 non-null   str
 15  Contract          7032 non-null   str
 16  PaperlessBilling  7032 non-null   str
 17  PaymentMethod     7032 non-null   str
 18  MonthlyCharges    7032 non-null   float64
 19  TotalCharges      7032 non-null   float64
 20  Churn             7032 non-null   str
dtypes: float64(2), int64(2), str(17)
memory usage: 1.9 MB

In [16]:
df.isnull().sum()

customerID          0
gender              0
SeniorCitizen       0
Partner             0
Dependents          0
tenure              0
PhoneService        0
MultipleLines       0
InternetService     0
OnlineSecurity      0
OnlineBackup        0
DeviceProtection    0
TechSupport         0
StreamingTV         0
StreamingMovies     0
Contract            0
PaperlessBilling    0
PaymentMethod       0
MonthlyCharges      0
TotalCharges        0
Churn               0
dtype: int64

In [19]:
df.to_csv(
    "E:/data_science/projects/customer_churn_prediction/data/processed/cleaned_telco_customer_churn.csv",
    index=False
)

In [20]:
# Load the cleaned dataset
cleaned_df = pd.read_csv("../data/processed/cleaned_telco_customer_churn.csv")

# Check its shape
cleaned_df.shape

(7032, 21)

In [21]:
cleaned_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 7032 entries, 0 to 7031
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customerID        7032 non-null   str
 1   gender            7032 non-null   str
 2   SeniorCitizen     7032 non-null   int64
 3   Partner           7032 non-null   str
 4   Dependents        7032 non-null   str
 5   tenure            7032 non-null   int64
 6   PhoneService      7032 non-null   str
 7   MultipleLines     7032 non-null   str
 8   InternetService   7032 non-null   str
 9   OnlineSecurity    7032 non-null   str
 10  OnlineBackup      7032 non-null   str
 11  DeviceProtection  7032 non-null   str
 12  TechSupport       7032 non-null   str
 13  StreamingTV       7032 non-null   str
 14  StreamingMovies   7032 non-null   str
 15  Contract          7032 non-null   str
 16  PaperlessBilling  7032 non-null   str
 17  PaymentMethod     7032 non-null   str
 18  MonthlyCharges    7032 non-null   float64
 19  TotalCharges      7032 non-null   float64
 20  Churn             7032 non-null   str
dtypes: float64(2), int64(2), str(17)
memory usage: 1.8 MB

## Data Cleaning Summary

The following cleaning operations were performed:

- Verified that no duplicate records exist.
- Identified hidden missing values in the `TotalCharges` column.
- Converted blank strings to `NaN`.
- Removed 11 records with missing `TotalCharges`.
- Converted `TotalCharges` to the `float64` data type.
- Saved the cleaned dataset for further analysis.